# Generated by Django 5.1.7 on 2025-03-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0003_chatgroup_is_private_chatgroup_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default='Hm8NwwVcnQrjSj4eJhPw3h', max_length=128, unique=True),
        ),
    ]
