# Generated by Django 5.1.7 on 2025-03-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0005_alter_chatgroup_group_name_alter_chatgroup_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='is_private',
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
