# Generated by Django 5.1.7 on 2025-03-28 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0007_privatechat_privatechatmessage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatechatmessage',
            name='chatroom',
        ),
        migrations.RemoveField(
            model_name='privatechatmessage',
            name='author',
        ),
        migrations.DeleteModel(
            name='PrivateChat',
        ),
        migrations.DeleteModel(
            name='PrivateChatMessage',
        ),
    ]
